_wandb:
    value:
        cli_version: 0.19.11
        code_path: code/collab-llm/scripts/dpo_train_offline_20q.py
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
                - 84
                - 95
                - 98
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.11
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
assistant_model_name:
    value: meta-llama/Llama-3.2-1B-Instruct
datasets:
    value:
        - aditijb/collabllm-20q
eval_steps:
    value: 1
gradient_accumulation_steps:
    value: 8
learning_rate:
    value: 5e-06
max_new_tokens:
    value: 256
max_prompt_length:
    value: 2048
minimum_gap:
    value: 0.1
n_eval_per_dataset:
    value: 30
num_train_epochs:
    value: 8
output_dir:
    value: ./train/20q/dpo_train_offline
per_device_train_batch_size:
    value: 2
probs:
    value:
        - 1
push_to_blob:
    value: false
push_to_hub:
    value: false
resume_ckpt_dir:
    value: null
run_name:
    value: null
save_total_limit:
    value: 10
seed:
    value: 42
